name: WaypointPlugin
version: 1.0
main: src.main.java.net.plugin.code.WaypointPlugin.java
commands:
  wpcreate:
    description: Creating a waypoint.
    usage: /wpcreate
  wpdelete:
    description: Deleting a waypoint.
    usage: /wpdelete